# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compare <- function(x, y) {
    .Call(`_rvfc_compare`, x, y)
}

mask <- function(x, y) {
    .Call(`_rvfc_mask`, x, y)
}

version <- function() {
    .Call(`_rvfc_version`)
}

